name: Build Custom DockDoor
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Download Code
        uses: actions/checkout@v4
      
      - name: Setup Latest Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '26.3.0'
          
      - name: Build the Mac App
        run: |
          # Added ASSETCATALOG_COMPILER_APPICON_NAME="" to bypass the buggy actool process
          # Added retry logic in case the runner crashes during the build
          for i in 1 2 3; do
            xcodebuild clean build -project DockDoor.xcodeproj -scheme DockDoor -configuration Release CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ASSETCATALOG_COMPILER_APPICON_NAME="" -derivedDataPath build_output && break || sleep 5;
          done
          
      - name: Zip the App
        run: |
          cd build_output/Build/Products/Release
          zip -r DockDoor-Custom.zip DockDoor.app
          
      - name: Upload to Browser
        uses: actions/upload-artifact@v4
        with:
          name: DockDoor-Custom-App
          path: build_output/Build/Products/Release/DockDoor-Custom.zip
